version: '3'

services:
  rutas-api:
    image: cesarurielhr/02_neo4j_api
    container_name: rutas-api
    ports:
      - "3000:3000"
    depends_on: 
      - neo4j
      - redis
    networks:
      - labs
  neo4j:
    image: neo4j
    container_name: neo1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    networks:
      - labs
  redis:
    image: redis/redis-stack:latest
    container_name: redis01
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - labs
networks:
  labs:
    driver: bridge
    
  
